spring.application.name=siga-fcte-pds-backend

# 1. Endereço do seu Banco de Dados (Troque 'nome_do_seu_banco' pelo nome real)
spring.datasource.url=jdbc:postgresql://localhost:5432/sigafctepds_db

# 2. Suas credenciais do Postgres
spring.datasource.username=postgres
spring.datasource.password=bdsigapds
#sua_senha_aqui
# 3. A mágica da reengenharia: O Hibernate cria as tabelas para você baseado no Java
# 'update' significa: se eu mudar a classe Aluno, mude a tabela no banco automaticamente.
spring.jpa.hibernate.ddl-auto=create-drop

# 4. Para você ver o SQL que o Spring está gerando no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true