spring.application.name=siga-fcte-pds-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/sigafctepds_db

spring.datasource.username=postgres
spring.datasource.password=bdsigapds


# 'update' significa: se mudar a classe Aluno, a tabela no banco vai mudar automaticamente.
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true